version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nms
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ../db/nms/data:/var/lib/postgresql/data
    restart: always
  nms:
    image: evgkoregin/nms:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - DB_MIKROBILL_URL=${DB_MIKROBILL_URL}
      - DB_MIKROBILL_USERNAME=${DB_MIKROBILL_USERNAME}
      - DB_MIKROBILL_PASSWORD=${DB_MIKROBILL_PASSWORD}
    volumes:
      - ../logs/nms:/nms/logs
    container_name: nms
    depends_on:
      - db
    ports:
      - "8999:8999"
