version: "3.9"
services:
  nms_db:
    image: postgres:15-alpine
    container_name: nms_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=nms
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./db/nms/data:/var/lib/postgresql/data
    restart: always

  mikrobill_db:
    image: mysql:8.0
    container_name: mikrobill_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/mikrobill:/var/lib/mysql
    restart: unless-stopped

  nms:
    image: evgkoregin/nms:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - DB_MIKROBILL_URL=${DB_MIKROBILL_URL}
      - DB_MIKROBILL_USERNAME=${DB_MIKROBILL_USERNAME}
      - DB_MIKROBILL_PASSWORD=${DB_MIKROBILL_PASSWORD}
    volumes:
      - ./logs/nms:/nms/logs
    container_name: nms
    depends_on:
      - nms_db
      - mikrobill_db
    ports:
      - "8999:8999"
