db:
  mikrobill:
    url: jdbc:mysql://localhost:3306/mikrobill?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_MIKROBILL_USERNAME:remote_nms}
    password: ${DB_MIKROBILL_PASSWORD:password}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nms
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

logging:
  level:
    org.springframework: INFO
    com.ekoregin.nms: INFO

server:
  error:
    include-stacktrace: always  # Показывает полный стек-трейс для отладки