server:
  port: 8999
  servlet:
    session:
      timeout: 60m

db:
  mikrobill:
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  application:
    name: nms
  profiles:
    active: dev
  devtools:
    add-properties: false
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    org.springframework: info
