server:
  port: 8999

db:
  mikrobill:
    url: jdbc:mysql://localhost:3306/mikrobill
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/nms
    username: postgres
    password: postgres
  #    mikrobill:
  #      url: jdbc:mysql://localhost:3306/mikrobill
  #      username: root
  #      password: password
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        show_sql: true
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.sql: info