server:
  port: 8999
  servlet:
    session:
      timeout: 60m

db:
  mikrobill:
    driver-class-name: com.mysql.cj.jdbc.Driver


spring:
  profiles:
    active: development
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
        show_sql: true
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  thymeleaf:
    cache: false
